-- ============================================================================
-- SCIFLOW SEED DATA (EMPTY)
-- 
-- This file is intentionally empty.
-- Real data is created through the app via wallet sign-in and bounty creation.
-- Run the migration (001_initial_schema.sql) first to create tables.
-- ============================================================================
