import { Bounty, Lab } from "@/types/bounty";

export const mockBounties: Bounty[] = [
  {
    id: "BNT-001",
    title: "Identify Actionable Mutations in Colorectal Cancer",
    description:
      "Comprehensive genomic sequencing project to identify actionable mutations in colorectal cancer tumors. The goal is to sequence tumors from diverse patient populations and identify novel therapeutic targets that can lead to personalized treatment approaches.",
    researchArea: "oncology",
    fundingAmount: 50000000,
    deadline: new Date("2027-12-31"),
    createdAt: new Date("2026-01-15"),
    status: "open",
    createdBy: "Cancer Research Foundation",
    objectives: [
      "Sequence 10,000+ colorectal cancer tumor samples",
      "Identify novel actionable mutations with therapeutic potential",
      "Develop mutation profile database for treatment matching",
      "Validate findings through in vitro studies",
      "Create predictive biomarker panel for patient stratification",
    ],
    deliverables: [
      "Complete genomic sequencing dataset",
      "Comprehensive mutation catalog with functional annotations",
      "Validated therapeutic target list",
      "Published research findings in peer-reviewed journals",
      "Open-access database for clinical use",
    ],
    applicantsCount: 12,
    tags: [
      "cancer",
      "genomics",
      "precision medicine",
      "tumor sequencing",
      "therapeutic targets",
    ],
    urgency: "critical",
    estimatedDuration: "24 months",
    milestones: [
      {
        id: "M1",
        title: "Sample Collection & Initial Sequencing",
        description: "Collect and sequence first 3,000 samples",
        fundingAmount: 15000000,
        deadline: new Date("2026-09-30"),
        status: "pending",
      },
      {
        id: "M2",
        title: "Mutation Analysis & Target Identification",
        description: "Complete bioinformatics analysis and identify targets",
        fundingAmount: 20000000,
        deadline: new Date("2027-06-30"),
        status: "pending",
      },
      {
        id: "M3",
        title: "Validation & Publication",
        description: "Validate findings and publish results",
        fundingAmount: 15000000,
        deadline: new Date("2027-12-31"),
        status: "pending",
      },
    ],
  },
  {
    id: "BNT-002",
    title: "Novel Immunotherapy for Glioblastoma",
    description:
      "Develop and test a novel CAR-T cell therapy targeting glioblastoma-specific antigens. This project aims to overcome the blood-brain barrier challenge and create an effective immunotherapy for this aggressive brain cancer.",
    researchArea: "oncology",
    fundingAmount: 35000000,
    deadline: new Date("2028-06-30"),
    createdAt: new Date("2026-01-10"),
    status: "open",
    createdBy: "Brain Cancer Alliance",
    objectives: [
      "Identify glioblastoma-specific surface antigens",
      "Engineer CAR-T cells for blood-brain barrier penetration",
      "Complete preclinical safety and efficacy studies",
      "Obtain IND approval for Phase I clinical trial",
      "Complete Phase I trial with 30 patients",
    ],
    deliverables: [
      "CAR-T cell manufacturing protocol",
      "Preclinical study results",
      "IND application and approval",
      "Phase I clinical trial data",
      "Published safety and efficacy data",
    ],
    applicantsCount: 8,
    tags: [
      "immunotherapy",
      "CAR-T",
      "brain cancer",
      "glioblastoma",
      "clinical trial",
    ],
    urgency: "high",
    estimatedDuration: "30 months",
  },
  {
    id: "BNT-003",
    title: "Alzheimer's Disease Early Detection Biomarkers",
    description:
      "Discover and validate blood-based biomarkers for early detection of Alzheimer's disease, potentially 10-15 years before symptom onset. Enable early intervention and improve patient outcomes.",
    researchArea: "neuroscience",
    fundingAmount: 25000000,
    deadline: new Date("2027-09-30"),
    createdAt: new Date("2026-01-08"),
    status: "in_progress",
    createdBy: "Neuroscience Research Institute",
    acceptedLabId: "LAB-003",
    acceptedLabName: "NeuroDiscovery Institute",
    objectives: [
      "Analyze blood samples from 5,000 participants",
      "Identify protein and metabolite biomarker candidates",
      "Validate biomarkers in independent cohort",
      "Develop diagnostic assay prototype",
      "Achieve >90% sensitivity and specificity",
    ],
    deliverables: [
      "Biomarker discovery dataset",
      "Validated biomarker panel",
      "Diagnostic assay prototype",
      "Clinical validation study results",
      "FDA breakthrough designation application",
    ],
    applicantsCount: 15,
    tags: [
      "Alzheimer's",
      "biomarkers",
      "diagnostics",
      "neurodegenerative",
      "early detection",
    ],
    urgency: "high",
    estimatedDuration: "20 months",
  },
  {
    id: "BNT-004",
    title: "Universal Flu Vaccine Development",
    description:
      "Develop a universal influenza vaccine that provides protection against all influenza A and B strains, eliminating the need for annual vaccination and preparing for pandemic threats.",
    researchArea: "infectious_disease",
    fundingAmount: 45000000,
    deadline: new Date("2029-03-31"),
    createdAt: new Date("2026-01-05"),
    status: "open",
    createdBy: "Global Health Foundation",
    objectives: [
      "Identify conserved influenza epitopes across all strains",
      "Design and synthesize vaccine candidates",
      "Complete animal model efficacy studies",
      "Demonstrate broad strain protection",
      "Complete Phase I/II human trials",
    ],
    deliverables: [
      "Vaccine candidate formulation",
      "Preclinical immunogenicity and efficacy data",
      "GMP manufacturing process",
      "Phase I/II clinical trial results",
      "Regulatory pathway recommendation",
    ],
    applicantsCount: 6,
    tags: [
      "vaccine",
      "influenza",
      "infectious disease",
      "pandemic preparedness",
      "immunology",
    ],
    urgency: "medium",
    estimatedDuration: "36 months",
  },
  {
    id: "BNT-005",
    title: "CRISPR Gene Therapy for Sickle Cell Disease",
    description:
      "Develop a one-time curative CRISPR-based gene therapy for sickle cell disease, targeting the underlying genetic mutation with high precision and minimal off-target effects.",
    researchArea: "genetics",
    fundingAmount: 40000000,
    deadline: new Date("2028-12-31"),
    createdAt: new Date("2025-12-20"),
    status: "open",
    createdBy: "Rare Disease Foundation",
    objectives: [
      "Optimize CRISPR editing for HBB gene correction",
      "Achieve >80% editing efficiency in HSCs",
      "Demonstrate no off-target effects",
      "Complete preclinical safety studies",
      "Initiate Phase I/II clinical trial",
    ],
    deliverables: [
      "Optimized CRISPR editing system",
      "Editing efficiency and specificity data",
      "Preclinical safety and efficacy package",
      "IND approval",
      "Enrollment of first 10 patients",
    ],
    applicantsCount: 10,
    tags: [
      "CRISPR",
      "gene therapy",
      "sickle cell",
      "rare disease",
      "genome editing",
    ],
    urgency: "high",
    estimatedDuration: "32 months",
  },
  {
    id: "BNT-006",
    title: "Microbiome-Based Treatment for IBD",
    description:
      "Develop a microbiome-based therapeutic intervention for inflammatory bowel disease (IBD) that restores healthy gut flora and reduces inflammation without immunosuppression.",
    researchArea: "immunology",
    fundingAmount: 18000000,
    deadline: new Date("2027-06-30"),
    createdAt: new Date("2025-12-15"),
    status: "completed",
    createdBy: "Digestive Health Institute",
    acceptedLabId: "LAB-005",
    acceptedLabName: "Microbiome Therapeutics Lab",
    objectives: [
      "Characterize healthy vs. IBD microbiomes",
      "Identify therapeutic bacterial consortia",
      "Develop stable formulation",
      "Complete Phase II efficacy trial",
      "Demonstrate disease remission in 60% of patients",
    ],
    deliverables: [
      "Microbiome characterization dataset",
      "Therapeutic bacterial cocktail formulation",
      "Manufacturing and stability protocols",
      "Phase II clinical trial results",
      "Regulatory submission package",
    ],
    applicantsCount: 9,
    tags: [
      "microbiome",
      "IBD",
      "gut health",
      "probiotics",
      "inflammation",
    ],
    urgency: "medium",
    estimatedDuration: "18 months",
  },
  {
    id: "BNT-007",
    title: "AI-Powered Drug Discovery for Rare Diseases",
    description:
      "Build an AI platform that can identify drug candidates for rare diseases with limited patient data, focusing on diseases affecting fewer than 10,000 patients globally.",
    researchArea: "drug_discovery",
    fundingAmount: 30000000,
    deadline: new Date("2028-03-31"),
    createdAt: new Date("2025-12-01"),
    status: "open",
    createdBy: "Tech for Good Foundation",
    objectives: [
      "Develop AI models for rare disease target prediction",
      "Create database of rare disease molecular signatures",
      "Identify 50 novel drug candidates",
      "Validate 10 candidates in disease models",
      "Advance 3 candidates to preclinical development",
    ],
    deliverables: [
      "AI drug discovery platform",
      "Rare disease molecular database",
      "Candidate drug list with validation data",
      "Preclinical package for top 3 candidates",
      "Open-source tools for rare disease research",
    ],
    applicantsCount: 14,
    tags: [
      "AI",
      "drug discovery",
      "rare disease",
      "machine learning",
      "orphan drugs",
    ],
    urgency: "medium",
    estimatedDuration: "26 months",
  },
  {
    id: "BNT-008",
    title: "Rapid Diagnostic for Antibiotic-Resistant Infections",
    description:
      "Create a point-of-care diagnostic device that can identify antibiotic-resistant bacterial infections within 30 minutes, enabling appropriate antibiotic selection and reducing resistance development.",
    researchArea: "diagnostics",
    fundingAmount: 22000000,
    deadline: new Date("2027-12-31"),
    createdAt: new Date("2025-11-28"),
    status: "in_progress",
    createdBy: "Antimicrobial Resistance Coalition",
    acceptedLabId: "LAB-004",
    acceptedLabName: "Rapid Diagnostics Lab",
    objectives: [
      "Develop molecular detection method for resistance genes",
      "Create portable diagnostic device prototype",
      "Validate against 20 common pathogens",
      "Achieve 95% accuracy in clinical samples",
      "Obtain FDA breakthrough designation",
    ],
    deliverables: [
      "Working diagnostic device prototype",
      "Clinical validation study results",
      "Manufacturing specifications",
      "Regulatory submission package",
      "Cost analysis for market viability",
    ],
    applicantsCount: 11,
    tags: [
      "diagnostics",
      "antibiotic resistance",
      "point-of-care",
      "infectious disease",
      "medical device",
    ],
    urgency: "critical",
    estimatedDuration: "24 months",
  },
];

export const mockLabs: Lab[] = [
  {
    id: "LAB-001",
    name: "Genomics Innovation Center",
    description:
      "Leading genomics research facility specializing in cancer genomics, precision medicine, and large-scale sequencing projects. State-of-the-art infrastructure with 50+ Illumina NovaSeq instruments.",
    specializations: ["oncology", "genetics", "diagnostics"],
    location: "Boston, MA, USA",
    website: "https://genomicsinnovation.org",
    logoUrl: "/labs/genomics-innovation.png",
    established: 2008,
    teamSize: 145,
    completedBounties: 23,
    activeBounties: 5,
    successRate: 92,
    rating: 4.8,
    totalFundingReceived: 285000000,
    publications: 340,
    verified: true,
    capabilities: [
      "Whole genome sequencing",
      "RNA-seq",
      "Single-cell sequencing",
      "Bioinformatics analysis",
      "Variant calling",
      "Data management",
    ],
    equipment: [
      "Illumina NovaSeq 6000 (50 units)",
      "10x Genomics Chromium",
      "Oxford Nanopore PromethION",
      "High-performance computing cluster (10,000 cores)",
      "Automated sample preparation systems",
    ],
  },
  {
    id: "LAB-002",
    name: "ImmunoTherapeutics Research Institute",
    description:
      "Pioneering immunotherapy development center with expertise in CAR-T cell engineering, cancer vaccines, and checkpoint inhibitor development. GMP manufacturing capabilities on-site.",
    specializations: ["oncology", "immunology", "drug_discovery"],
    location: "San Francisco, CA, USA",
    website: "https://immunotherapeutics.org",
    logoUrl: "/labs/immunotherapeutics.png",
    established: 2012,
    teamSize: 98,
    completedBounties: 15,
    activeBounties: 3,
    successRate: 88,
    rating: 4.7,
    totalFundingReceived: 198000000,
    publications: 156,
    verified: true,
    capabilities: [
      "CAR-T cell engineering",
      "T cell expansion",
      "Cancer vaccine development",
      "Antibody engineering",
      "GMP manufacturing",
      "Clinical trial management",
    ],
    equipment: [
      "GMP cell manufacturing suite",
      "Flow cytometry core facility",
      "Confocal microscopy",
      "CRISPR editing platforms",
      "Automated cell culture systems",
    ],
  },
  {
    id: "LAB-003",
    name: "NeuroDiscovery Institute",
    description:
      "Specialized neuroscience research center focused on neurodegenerative diseases, biomarker discovery, and brain imaging. Unique access to longitudinal patient cohorts spanning 20+ years.",
    specializations: ["neuroscience", "diagnostics", "drug_discovery"],
    location: "Cambridge, UK",
    website: "https://neurodiscovery.ac.uk",
    logoUrl: "/labs/neurodiscovery.png",
    established: 2005,
    teamSize: 112,
    completedBounties: 19,
    activeBounties: 4,
    successRate: 95,
    rating: 4.9,
    totalFundingReceived: 234000000,
    publications: 478,
    verified: true,
    capabilities: [
      "Biomarker discovery",
      "Mass spectrometry",
      "Proteomics",
      "Brain imaging (fMRI, PET)",
      "Clinical cohort management",
      "Data analytics",
    ],
    equipment: [
      "Orbitrap mass spectrometers",
      "7T MRI scanner",
      "PET-CT scanner",
      "Brain tissue biobank",
      "Automated immunoassay platforms",
    ],
  },
  {
    id: "LAB-004",
    name: "Rapid Diagnostics Lab",
    description:
      "Innovation hub for point-of-care diagnostics and medical device development. Expertise in microfluidics, biosensors, and rapid molecular detection technologies.",
    specializations: ["diagnostics", "infectious_disease"],
    location: "Singapore",
    website: "https://rapiddiagnostics.sg",
    logoUrl: "/labs/rapid-diagnostics.png",
    established: 2015,
    teamSize: 67,
    completedBounties: 12,
    activeBounties: 2,
    successRate: 90,
    rating: 4.6,
    totalFundingReceived: 145000000,
    publications: 98,
    verified: true,
    capabilities: [
      "Microfluidic device design",
      "Biosensor development",
      "Molecular diagnostics",
      "Prototype manufacturing",
      "Clinical validation",
      "Regulatory consulting",
    ],
    equipment: [
      "Microfluidics fabrication facility",
      "PCR and isothermal amplification platforms",
      "Surface plasmon resonance",
      "Electrochemical testing systems",
      "3D printing for prototyping",
    ],
  },
  {
    id: "LAB-005",
    name: "Microbiome Therapeutics Lab",
    description:
      "Leading microbiome research facility developing next-generation live biotherapeutics. Specializes in gut microbiome analysis, bacterial strain isolation, and therapeutic formulation.",
    specializations: ["immunology", "drug_discovery", "infectious_disease"],
    location: "Utrecht, Netherlands",
    website: "https://microbiometherapeutics.nl",
    logoUrl: "/labs/microbiome-therapeutics.png",
    established: 2013,
    teamSize: 54,
    completedBounties: 8,
    activeBounties: 1,
    successRate: 87,
    rating: 4.5,
    totalFundingReceived: 92000000,
    publications: 124,
    verified: true,
    capabilities: [
      "Microbiome sequencing and analysis",
      "Bacterial strain isolation and characterization",
      "Anaerobic culture techniques",
      "Formulation development",
      "Clinical trial design",
      "GMP bacterial manufacturing",
    ],
    equipment: [
      "Anaerobic culture chambers",
      "Metagenomic sequencing platforms",
      "Bacterial biobank (5,000+ strains)",
      "Fermentation systems",
      "Freeze-drying equipment",
    ],
  },
  {
    id: "LAB-006",
    name: "Gene Editing Excellence Center",
    description:
      "World-class gene editing research institute with expertise in CRISPR, base editing, and prime editing. Pioneers in developing safer and more precise genome editing tools for therapeutic applications.",
    specializations: ["genetics", "rare_disease", "drug_discovery"],
    location: "Basel, Switzerland",
    website: "https://geneediting.ch",
    logoUrl: "/labs/gene-editing.png",
    established: 2010,
    teamSize: 89,
    completedBounties: 17,
    activeBounties: 4,
    successRate: 94,
    rating: 4.8,
    totalFundingReceived: 215000000,
    publications: 267,
    verified: true,
    capabilities: [
      "CRISPR-Cas9 editing",
      "Base editing",
      "Prime editing",
      "Off-target analysis",
      "HSC manipulation",
      "Ex vivo gene therapy",
    ],
    equipment: [
      "CRISPR screening platforms",
      "High-throughput sequencing",
      "Cell sorting facilities",
      "Stem cell culture systems",
      "NGS for off-target detection",
    ],
  },
  {
    id: "LAB-007",
    name: "AI Drug Discovery Institute",
    description:
      "Computational drug discovery powerhouse combining artificial intelligence, quantum chemistry, and high-throughput screening. Specialized in discovering drugs for complex and rare diseases.",
    specializations: ["drug_discovery", "rare_disease", "oncology"],
    location: "Toronto, Canada",
    website: "https://aidrugdiscovery.ca",
    logoUrl: "/labs/ai-drug-discovery.png",
    established: 2017,
    teamSize: 73,
    completedBounties: 11,
    activeBounties: 3,
    successRate: 91,
    rating: 4.7,
    totalFundingReceived: 167000000,
    publications: 142,
    verified: true,
    capabilities: [
      "AI/ML for drug discovery",
      "Virtual screening",
      "Molecular dynamics simulation",
      "High-throughput screening",
      "Medicinal chemistry",
      "Structure-based design",
    ],
    equipment: [
      "GPU clusters for ML training",
      "Automated compound library (1M+ compounds)",
      "High-throughput screening robots",
      "X-ray crystallography",
      "Cryo-EM facility",
    ],
  },
  {
    id: "LAB-008",
    name: "Cardiac Innovation Laboratory",
    description:
      "Premier cardiovascular research center developing novel therapies for heart disease. Expertise in cell therapy, tissue engineering, and regenerative medicine for cardiac applications.",
    specializations: ["cardiology", "drug_discovery", "genetics"],
    location: "Houston, TX, USA",
    website: "https://cardiacinnovation.org",
    logoUrl: "/labs/cardiac-innovation.png",
    established: 2009,
    teamSize: 82,
    completedBounties: 14,
    activeBounties: 2,
    successRate: 89,
    rating: 4.6,
    totalFundingReceived: 178000000,
    publications: 203,
    verified: true,
    capabilities: [
      "Cardiac cell therapy",
      "Tissue engineering",
      "iPSC-derived cardiomyocytes",
      "Gene therapy for heart disease",
      "Preclinical cardiac models",
      "Clinical trial execution",
    ],
    equipment: [
      "3D bioprinting systems",
      "Perfusion bioreactors",
      "Cardiac imaging suite",
      "iPSC culture facilities",
      "Animal surgery suites",
    ],
  },
];
